restylers_version: dev
restylers:
  - fourmolu
  - stylish-haskell:
      enabled: false
  - prettier-markdown:
      enabled: false
  - whitespace:
      include:
        - "**/*"
        - "!**/*.t" # cram tests have whitespace in assertions
        - "!README.md" # help code blocks have trailing whitespace
  - "*"
