name: stackctl
version: 1.6.0.0
github: freckle/stackctl
license: MIT
author: Freckle Engineering
maintainer: freckle-engineering@renaissance.com
copyright: 2022 Renaissance Learning Inc

extra-doc-files:
  - README.md
  - CHANGELOG.md

description: Please see <https://github.com/freckle/stackctl#readme>

dependencies:
  - base >= 4 && < 5

ghc-options:
  - -fignore-optim-changes
  - -fwrite-ide-info
  - -Weverything
  - -Wno-all-missed-specialisations
  - -Wno-missed-specialisations
  - -Wno-missing-import-lists
  - -Wno-missing-kind-signatures
  - -Wno-missing-local-signatures
  - -Wno-missing-safe-haskell-mode
  - -Wno-prepositive-qualified-module
  - -Wno-unsafe
  - -optP-Wno-nonportable-include-path # workaround [Filename case on macOS · Issue #4739 · haskell/cabal](https://github.com/haskell/cabal/issues/4739)

default-extensions:
  - BangPatterns
  - DataKinds
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - DerivingVia
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeFamilies

library:
  source-dirs: src
  dependencies:
    - Blammo >= 1.1.2.1 # getColorsLogger, etc
    - Glob
    - QuickCheck
    - aeson
    - aeson-casing
    - aeson-pretty
    - amazonka >= 2.0
    - amazonka-cloudformation >= 2.0
    - amazonka-core >= 2.0
    - amazonka-ec2 >= 2.0
    - amazonka-lambda >= 2.0
    - amazonka-mtl
    - amazonka-sso >= 2.0
    - amazonka-sts >= 2.0
    - bytestring
    - cfn-flip >= 0.1.0.3 # bugfix for Condition
    - conduit
    - containers
    - envparse
    - errors
    - exceptions
    - extra
    - filepath
    - lens
    - lens-aeson
    - monad-logger
    - mtl
    - optparse-applicative
    - resourcet
    - rio
    - semigroups
    - text
    - text-metrics
    - time
    - transformers
    - typed-process
    - unliftio >= 0.2.25.0 # UnliftIO.Exception.Lens
    - unordered-containers
    - uuid
    - yaml

executables:
  stackctl:
    main: Main.hs
    source-dirs: app
    dependencies:
      - stackctl
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - Blammo
      - Glob
      - QuickCheck
      - aeson
      - amazonka-ec2
      - amazonka-mtl
      - bytestring
      - filepath
      - hspec
      - hspec-expectations-lifted
      - hspec-golden >= 0.2.1.0
      - lens
      - mtl
      - stackctl
      - yaml
