resolver: lts-19.28

extra-deps:
  - Blammo-1.0.3.0
  - cfn-flip-0.1.0.2

  # For Blammo
  - monad-logger-aeson-0.4.0.2
  - context-0.2.0.1

  - github: brendanhay/amazonka
    commit: f73a957d05f64863e867cf39d0db260718f0fadd # main, as of SSO support
    subdirs:
      - lib/amazonka
      - lib/amazonka-core
      - lib/services/amazonka-cloudformation
      - lib/services/amazonka-certificatemanager
      - lib/services/amazonka-ec2
      - lib/services/amazonka-ecr
      - lib/services/amazonka-sso
      - lib/services/amazonka-sts

  # For weeder-2.3.0
  - algebraic-graphs-0.5
