resolver: lts-20.4

extra-deps:
  - Blammo-1.1.2.1
  - cfn-flip-0.1.0.3
  - unliftio-0.2.25.0

  - amazonka-2.0
  - amazonka-core-2.0
  - amazonka-certificatemanager-2.0
  - amazonka-cloudformation-2.0
  - amazonka-ec2-2.0
  - amazonka-ecr-2.0
  - amazonka-lambda-2.0
  - amazonka-sso-2.0
  - amazonka-sts-2.0

  # For amazonka-core-2.0
  - crypton-0.33
