name: Release

on:
  push:
    branches:
      - main
      - rc/*

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            suffix: x86_64-linux
          - os: macOS-latest
            suffix: x86_64-osx

    runs-on: ${{ matrix.os }}
    steps:
      - if: ${{ runner.os == 'macOS' }}
        run: brew install coreutils # need GNU install
      - run: gem install --user ronn-ng
      - run: |
          for bin in "$HOME"/.local/share/gem/ruby/*/bin; do
            echo "$bin"
          done >>"$GITHUB_PATH"
      - uses: actions/checkout@v4

      - id: release
        uses: cycjimmy/semantic-release-action@v4
        with:
          dry_run: true
          extra_plugins: |
            semantic-release-stack-upload
        env:
          FORCE_COLOR: 1
          PREPARE_IN_VERIFY: 1

          # These are unused, but needed for verify to succeed
          GITHUB_TOKEN: ${{ github.token }}
          HACKAGE_KEY: ${{ secrets.HACKAGE_UPLOAD_API_KEY }}

      - uses: freckle/stack-action@v5
      - run: |
          make install.check # creates dist/stackctl.tar.gz
          cp -v dist/stackctl.tar.gz stackctl-${{ matrix.suffix }}.tar.gz
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-binaries
          path: "stackctl-*.tar.gz"
          if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/download-artifact@v5

      - id: token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.FRECKLE_AUTOMATION_APP_ID }}
          private-key: ${{ secrets.FRECKLE_AUTOMATION_PRIVATE_KEY }}

      - id: release
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            semantic-release-stack-upload
        env:
          FORCE_COLOR: 1
          GITHUB_TOKEN: ${{ steps.token.outputs.token }}
          HACKAGE_KEY: ${{ secrets.HACKAGE_UPLOAD_API_KEY }}
