name: Release

on:
  push:
    branches: main

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: tag
        uses: freckle/haskell-tag-action@v1
    outputs:
      tag: ${{ steps.tag.outputs.tag }}

  create-release:
    needs: tag
    if: needs.tag.outputs.tag
    runs-on: ubuntu-latest
    steps:
      - id: create-release
        uses: freckle/action-gh-release@v2
        with:
          tag_name: ${{ needs.tag.outputs.tag }}
          generate_release_notes: true
          draft: true
    outputs:
      release_id: ${{ steps.create-release.outputs.id }}

  upload-assets:
    needs: create-release
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            suffix: x86_64-linux
          - os: macOS-latest
            suffix: x86_64-osx

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: freckle/stack-cache-action@v2
      - run: echo "$HOME/.local/share/gem/ruby/3.0.0/bin" >>"$GITHUB_PATH"
      - run: gem install --user ronn-ng
      - if: ${{ runner.os == 'macOS' }}
        run: brew install coreutils # need GNU install
      - run: |
          make install.check # creates dist/stackctl.tar.gz
          cp -v dist/stackctl.tar.gz stackctl-${{ matrix.suffix }}.tar.gz
      - uses: freckle/action-gh-release@v2
        with:
          id: ${{ needs.create-release.outputs.release_id }}
          files: "*-${{ matrix.suffix }}.tar.gz"
          fail_on_unmatched_files: true

  publish-release:
    needs:
      - create-release
      - upload-assets
    runs-on: ubuntu-latest
    steps:
      - uses: freckle/action-gh-release@v2
        with:
          id: ${{ needs.create-release.outputs.release_id }}
          draft: false

  upload-hackage:
    needs: tag
    if: needs.tag.outputs.tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: freckle/stack-upload-action@v2
        env:
          HACKAGE_API_KEY: ${{ secrets.HACKAGE_UPLOAD_API_KEY }}
