name: Release

on:
  push:
    branches:
      - main
      - rc/*

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            suffix: x86_64-linux
          - os: macOS-latest
            suffix: x86_64-osx

    runs-on: ${{ matrix.os }}
    steps:
      # stack was removed in macOS-14 which is now latest
      # https://discourse.haskell.org/t/github-hosted-runner-for-macos-aarch64/8717/16
      - if: ${{ runner.os == 'macOS' }}
        run: curl -sSL https://get.haskellstack.org/ | sh

      - uses: actions/checkout@v4
      - uses: freckle/stack-cache-action@v2
      - run: gem install --user ronn-ng
      - run: |
          for bin in "$HOME"/.local/share/gem/ruby/*/bin; do
            echo "$bin"
          done >>"$GITHUB_PATH"
      - if: ${{ runner.os == 'macOS' }}
        run: brew install coreutils # need GNU install
      - run: |
          make install.check # creates dist/stackctl.tar.gz
          cp -v dist/stackctl.tar.gz stackctl-${{ matrix.suffix }}.tar.gz
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-binaries
          path: "stackctl-*.tar.gz"
          if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/download-artifact@v4

      - id: token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.FRECKLE_AUTOMATION_APP_ID }}
          private-key: ${{ secrets.FRECKLE_AUTOMATION_PRIVATE_KEY }}

      - id: release
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            git+https://github.com/pbrisbin/semantic-release-stack-upload.git
        env:
          FORCE_COLOR: 1
          GITHUB_TOKEN: ${{ steps.token.outputs.token }}
          HACKAGE_KEY: ${{ secrets.HACKAGE_UPLOAD_API_KEY }}
          STACK_YAML: stack-lts-20.4.yaml
